lazy loading module support
ngx-grpc/ngx-grpc pull request #24
Opened 2020-09-18 11:17 UTC by Greegko

If the root changes into any it will allows you to configure the hostnames in lazy loaded modules

https://angular.io/guide/providers#limiting-provider-scope-by-lazy-loading-modules

Resolves #18

2020-09-18 12:16 UTC, Greegko commented
Just noticed, this only supported by Angular 9+, not sure what's your target Angular version what you want to support.

2020-09-18 16:14 UTC, hellraisercenobit requested changes
We could add providedIn: 'any', on grpc-console-logger-interceptor.ts too 👍

2020-09-22 12:57 UTC, smnbbrv commented
Hi @Greegko 
Hi @hellraisercenobit 

I would need some time to think on this change. This can be breaking since it is not really expected (at least as I see) that in lazy loaded modules all the services will get duplicated. This can lead to problems with e.g. interceptors that are developed to be singletons.

Example: interceptor stores some class-level property and expects this property to always have this value, since everybody is used to this service behaviour. If the service is not unique (not a singleton) this logic gets completely broken.

Another problem here is that I cannot change `any` to `root` if I want to. E.g. if the grpc things are loaded from the project start, there is a performance loss in this approach: instead of having one service there are tons of them for each module.

Ideally, this should be configurable and maybe the approach with `any` does not really work here.

I don't say we don't do this, but this is a breaking change and we need to make it carefully.

2020-09-22 13:17 UTC, hellraisercenobit commented
Hello @smnbbrv @Greegko , maybe a better solution could be to add a parameter in the ngx-codegen to specify exactly what we want.
providedIn property support a module instance like => providedIn: MyCustomModule for isolation.
So by default we could have root, and others values could be 'all' or a specific module.
What do you think about this?

2020-10-22 10:46 UTC, Greegko commented
Hey @smnbbrv, any progress about this ? For us it is a blocker, we would need this to move forward with the migration.

2020-10-22 11:47 UTC, hellraisercenobit commented
all tokens need this fix. not just services.
GRPC_CONSOLE_LOGGER_ENABLED
GRPC_INTERCEPTORS
GRPC_WORKER
should be configurable too in a feature module.

2020-11-26 19:58 UTC, smnbbrv commented
Hi guys,

please check version 2.0.0. As promised, the issue wasn't forgotten.

I hope you can finally use it in the lazy modules :)

2020-11-26 19:58 UTC, closed without merging

2020-11-27 08:26 UTC, hellraisercenobit commented
Lot of work in v2 !
Awesome!

2020-11-27 18:45 UTC, hellraisercenobit commented
After some tests, it works like a charm!
Easy configuration, nice forRoot ForChild feature 👍

2020-11-27 19:39 UTC, smnbbrv commented
Thank you very much for the feedback 🙂 I also like it way more now... let's see how it develops